spring:
  datasource:
    url: jdbc:mysql://${RDS_HOSTNAME:localhost}:${RDS_PORT:3306}/${RDS_DB_NAME:product}
    username: ${RDS_USERNAME:admin}
    password: ${RDS_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    serialization:
      write-dates-as-timestamps: false

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update